run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive
    - unconvert
    - unparam
    - gosec
    - exportloopref
    - prealloc

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true
    disable:
      - shadow

  gofmt:
    simplify: true

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint

  revive:
    rules:
      - name: unexported-return
        disabled: true

  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G304 # File path provided as taint input

issues:
  exclude-dirs:
    - vendor

  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
