version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: anvil
    main: ./cmd/anvil
    binary: anvil
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: anvil
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: siddharth-bhatnagar
    name: anvil
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"

brews:
  - repository:
      owner: siddharth-bhatnagar
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/siddharth-bhatnagar/anvil
    description: A terminal-based agentic coding CLI
    license: MIT
    test: |
      system "#{bin}/anvil --version"
    install: |
      bin.install "anvil"
